### ISSUE TITLE
[feature] Markdown format for Posts

### ISSUE THREAD

**Issue by manfre** [andrewgodwin/takahe#10]
Support using Markdown format when creating a Post.

* Add per User setting for "Default post format"
* Add "Post format" drop down when drafting/editing a post
* Add `content_raw` and `content_format` fields to `Post` that only apply to `local == True`

Questions:

* @andrewgodwin is this a feature you want to support?
* Is it worth breaking consistency to save space and only store html formatted posts in `Post.content` and leave `Post.content_raw = None`?

**Comment by andrewgodwin** [comment]
So the thing here is - what format would you apply? Mastodon only accepts links, newlines, and paragraphs - no bold, italic, custom styling, etc. Adding any other formatting would get stripped away by the large majority of clients, and I don't really want to have a separate local format that works only locally as it might mislead people into thinking their formatting works everywhere.

**Comment by manfre** [comment]
I didn't realize it sanitized the html as aggressively as it does [1]. Without those, the only remaining formatting that I'd use regularly is `[text](link)`, but that's easy enough to type out as html. 

Closing issue.

[1] [ActivityPub HTML Sanitization](https://docs.joinmastodon.org/spec/activitypub/#sanitization)
