### ISSUE TITLE
Run the tests in GitHub Actions

### ISSUE THREAD

**Issue by simonw** [andrewgodwin/takahe#11]
It looks like CI isn't up and running yet. Would you be interested in a PR that sets that up with GitHub Actions?

I run CI against a Django app that uses PostgreSQL in https://github.com/natbat/pillarpointstewards/blob/main/.github/workflows/test.yml - I can adapt that for this repo if it would be useful.

**Comment by andrewgodwin** [comment]
I was waiting to set that up myself once I have more tests, but if you want to get me a ready-made one I'll take it!

**Comment by simonw** [comment]
PR:
- #13
