### ISSUE TITLE
500 on add profile pic to identity via frontend

### ISSUE THREAD

**Issue by whatSocks** [andrewgodwin/takahe#14]
Is it me or is profile image functionality not working yet?

**Comment by manfre** [comment]
More context needed. 

* Can you share the traceback that would have dumped to the logs?
* How is your media storage configured? E.g. what value for `TAKAHE_MEDIA_BACKEND`? Is the backend configured properly?

**Comment by whatSocks** [comment]
Sorry - 
I'm using docker, so:

```
- "TAKAHE_MEDIA_BACKEND=local"
```

I am able to add image to my identity by the admin but not via the frontend.

**Comment by andrewgodwin** [comment]
This should be fixed by #19 - let us know if not and paste the traceback you get when you try and upload via the frontend.

(uploading via the admin backend doesn't resize it, which might not be great if you give it a massive image)

**Comment by whatSocks** [comment]
<img width="626" alt="Screen Shot 2022-11-20 at 2 55 10 PM" src="https://user-images.githubusercontent.com/2731744/202923157-30d458da-465e-4bcf-a7d8-a3e7bdde5f6f.png">

pulled latest changes and 😬

**Comment by andrewgodwin** [comment]
Ah, you're using the docker-compose file - see discussion on #18, we should get that fixed shortly. For now, change "production" to "development" in the compose file and things should be alright again.
