### ISSUE TITLE
Docker use is... strange

### ISSUE THREAD

**Issue by danielquinn** [andrewgodwin/takahe#17]
On most projects, the `Dockefile` lives in the project root alongside `docker-compose.yaml` which, while annoying as it clutters up the root, makes actually using it quite easy:

```shell
$ git clone ...
cd takahe
docker-compose up
```

However in its current position living in `docker/`, it's not clear what I'm supposed to do there.  If I hop into that folder and run `docker-compose up`, it barfs, complaining that `requirements.txt` isn't available:

```shell
$ docker-compose up
[+] Running 9/10
 ⠿ web Warning                                                                                                                                                                1.7s
 ⠿ db Pulled                                                                                                                                                                 23.7s
   ⠿ ca7dd9ec2225 Pull complete                                                                                                                                               1.1s
   ⠿ 126ca7716c09 Pull complete                                                                                                                                               1.7s
   ⠿ 72a45366ffb3 Pull complete                                                                                                                                               1.9s
   ⠿ c4825ba03629 Pull complete                                                                                                                                              20.1s
   ⠿ 90d9e7b7d99d Pull complete                                                                                                                                              20.6s
   ⠿ a6f996156d58 Pull complete                                                                                                                                              20.8s
   ⠿ 4af28305ac48 Pull complete                                                                                                                                              21.0s
   ⠿ aae4e1126571 Pull complete                                                                                                                                              21.1s
[+] Building 1.0s (7/11)                                                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                                                          0.1s
 => => transferring dockerfile: 563B                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                             0.1s
 => => transferring context: 2B                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/python:3.11.0-slim-buster                                                                                                  0.6s
 => [1/7] FROM docker.io/library/python:3.11.0-slim-buster@sha256:e3168357ada3287cda4c79ecae7f5103cb4d071d9b610a1d9380ea4b7cfc981f                                            0.2s
 => => resolve docker.io/library/python:3.11.0-slim-buster@sha256:e3168357ada3287cda4c79ecae7f5103cb4d071d9b610a1d9380ea4b7cfc981f                                            0.1s
 => [internal] load build context                                                                                                                                             0.1s
 => => transferring context: 1.11kB                                                                                                                                           0.0s
 => CACHED [2/7] RUN apt-get update && apt-get -y install libpq-dev python3-dev build-essential                                                                               0.0s
 => ERROR [3/7] COPY requirements.txt requirements.txt                                                                                                                        0.0s
------
 > [3/7] COPY requirements.txt requirements.txt:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref 7a48jr0l5neg58npuq6aox6em::esv4uruqtuj3a07keyyaolx4y: "/requirements.txt": not found
```

If there's a trick to launching docker-compose via this separate folder, it'd be nice if it were documented in `CONTRIBUTING.md` or the README.  As it is, I just got it running by symlinking the files into the root which is obviously not ideal, but I couldn't figure out the expected way to do it:

```shell
$ cd takahe
$ ln -s docker/* .
$ docker-compose up
```

### Steps to reproduce

```
$ docker system prune --all --volumes --force
$ cd takahe/docker/
$ docker-compose up
```

**Comment by manfre** [comment]
**Note:** Takahe is experimental and deploying has not yet been fully documented, polished, and/or made ready for the general public.

When working with `docker` or `docker compose` where the context is different than the folder containing the configuration, you need to specify the config file with `-f` [1]. Storing docker configuration in a `docker/` folder is fairly common.

```bash
docker build -f docker/Dockerfile -t "takahe:latest" .
docker compose -f docker/docker-compose.yml up
```

[1] [Docker compose docs](https://docs.docker.com/engine/reference/commandline/compose/#use--f-to-specify-name-and-path-of-one-or-more-compose-files)

**Comment by jefftriplett** [comment]
I guess I use `docker compose -f ./path/to/docker-compose.yml {cmd}` enough that I didn't think twice when I saw this. Adding a note to the README or CONTRIBUTING.md for how to run this would be helpful, but that feels like a low-hanging fruit for a community contribution.

**Comment by danielquinn** [comment]
I guess the question should really be around how you intend to use the `docker-compose.yml` file, because currently, even running `$ docker compose -f docker/docker-compose.yml up` from the project root still dies with the same error unless the image is built manually first.  If it's meant to be a basis for development (as the hard-coded environment values in it suggest), then requiring (a) a manual `build` and not mounting `.:/takahe/` make this file far less useful than it could be.

It's fine either way if you want to keep the `docker/` folder and require the extra step, just not as friendly as it could be is all.

For a developer, here are the current steps:

```shell
$ docker build -f docker/Dockerfile -t "takahe:latest" .
$ docker compose -f docker/docker-compose.yaml up
```

while it could be:

```shell
$ docker-compose up
```

In either case, having that volume mount would be nice.

I guess I'll write a PR to give devs a heads-up for the first case.

**Comment by andrewgodwin** [comment]
Yeah, I don't actually use Docker for local development - I just run it on my laptop - so the compose file is not something I use. We should probably also have a Tilt file in there at this point I guess.

The docs are enough for now - thanks for those - and we'll re-evaluate this once I get to an actual release and ask for development help officially!
