### ISSUE TITLE
"This is a member of another server" for user on same server

### ISSUE THREAD

**Issue by whatSocks** [andrewgodwin/takahe#20]
For local testing purposes, I have to pick a domain to function on the app - I picked apple.sauce, made a user and made an identity: carrot@apple.sauce. 

I wanted to test follows, so I made a second user: otheruser@apple.sauce

Logged in as carrot, I found otheruser. Surprisingly, other user says "This is a member of another server." Is this expected behavior? 

<img width="654" alt="Screen Shot 2022-11-20 at 10 16 16 AM" src="https://user-images.githubusercontent.com/2731744/202910241-6ac5afcd-d0d0-4708-901a-6fa3ac3cfae9.png">

**Comment by whatSocks** [comment]
found the "Local" flag, issue solved

**Comment by andrewgodwin** [comment]
If you're making identities manually via the admin I'd not do that, as you'll skip things like setting the local flag and generating keys for them.
