### ISSUE TITLE
[Local Development Setup] - Instructions to handle CORS issues

### ISSUE THREAD

**Issue by whatSocks** [andrewgodwin/takahe#23]
Update instructions to help new users handle CORS issues - example, when adding images for use as banner. 

```
Forbidden (403)

CSRF verification failed. Request aborted.
Help

Reason given for failure:

    Origin checking failed - http://localhost:8000 does not match any trusted origins.
```

**Comment by andrewgodwin** [comment]
We have a bit of code in the development settings that forces everything to be HTTPS - let me go pull that out.

**Comment by whatSocks** [comment]
<img width="663" alt="Screen Shot 2022-11-20 at 4 00 56 PM" src="https://user-images.githubusercontent.com/2731744/202925893-1cf66668-ae71-4fc8-a0f7-5c85f4ca3dfe.png">


back in action!! thanks!
