### ISSUE TITLE
boosts / stars don't persist on refresh

### ISSUE THREAD

**Issue by whatSocks** [andrewgodwin/takahe#24]
I can boost / star a post but it doesn't stay selected on refresh. 
On Mastodon I can boost multiple times, but I have to "unboost" to boost again

**Comment by andrewgodwin** [comment]
Yes, I've seen this problem recently too. It's on my list to look at today.

**Comment by andrewgodwin** [comment]
Hmm, interesting, it's working on takahe.social for me now. Could you:
- Open the browser's network inspector and see if the HTTP request goes through alright
- Poke in the PostInteractions admin and see what state the interaction ends up in, or if it's even there?

**Comment by whatSocks** [comment]
the interactions are definitely being created, here's a fresh ⭐ 

<img width="663" alt="Screen Shot 2022-11-20 at 5 16 15 PM" src="https://user-images.githubusercontent.com/2731744/202929217-d480ae24-fb4b-4589-8ed6-6fe48e663f27.png">

**Comment by whatSocks** [comment]
list view 
<img width="1094" alt="Screen Shot 2022-11-20 at 5 17 25 PM" src="https://user-images.githubusercontent.com/2731744/202929282-26042bc6-8062-49d1-b324-4a753d7a6d40.png">

**Comment by andrewgodwin** [comment]
That's very odd as the code to make them stars checks for that exact thing: https://github.com/andrewgodwin/takahe/blob/main/activities/models/post_interaction.py#L159

It looks like Stator was not running here - if you run it, does it progress those interactions into `fanned_out`, and does that affect anything?

**Comment by whatSocks** [comment]
Fan outs work ...

<img width="1063" alt="Screen Shot 2022-11-20 at 11 56 31 PM" src="https://user-images.githubusercontent.com/2731744/202968667-c17c102a-5b62-4704-9c9f-f7c893e2d51a.png">

<img width="566" alt="Screen Shot 2022-11-20 at 11 58 04 PM" src="https://user-images.githubusercontent.com/2731744/202968844-4805e305-2101-48f7-ac3f-d0d543193a50.png">

And the UI works :) 

<img width="669" alt="Screen Shot 2022-11-20 at 11 59 39 PM" src="https://user-images.githubusercontent.com/2731744/202969047-bb4e96c6-9ac5-41d5-a54e-846e8ca93b10.png">

**Comment by whatSocks** [comment]
just forgot the manage.py runstator step
