### ISSUE TITLE
Markdown / Code snippets

### ISSUE THREAD

**Issue by shivan-s** [andrewgodwin/takahe#4]
Hello,

I know we are in very early stages. 

This is a very low low priority feature request. 

I'm wondering if we can get markdown or ability to show code in posts / toots.

Keep up the good work. And following this project closely.

Shivan

**Comment by andrewgodwin** [comment]
I'm afraid I won't be able to implement that sensibly, since I want to interoperate with Mastodon and it won't allow those HTML tags. Sorry!
