### ISSUE TITLE
Website crashes if local username is not on local instance

### ISSUE THREAD

**Issue by jfroehlich** [andrewgodwin/takahe#7]
Hi Andrew,

What: Requesting a URL in the browser with the handle of a non-existing user (on the instance) throws a server error:

- `https://takahe.social/@takahe/`  -> 500
- `https://takahe.social/@jfroehlich/` -> 500

Expected: Requesting the URL of a non-existing user in the browser should return a 404, i guess?

**Comment by andrewgodwin** [comment]
I just fixed this in https://github.com/andrewgodwin/takahe/commit/6e79527bb5743481148f492274b7a19da057366c!
